
spring:
  #thymeleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.54.65:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: blue
    password: 123456
    hikari:
      #连接池名（据说是最快的连接池）
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 18000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # redis配置
  redis:
    # 服务器地址
    host: 47.103.54.65:3306
    #端口号
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: PT10S
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 0


#Mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回数据别名（默认别名是类名）
  type-aliases-package: com.csl.seckill.pojo

logging:
  level:
    com.csl.seckill.mapper: debug

server:
  max-http-header-size: 40960
  port: 8099
